.TH VIEWNIOR 1 "December 14, 2010"
.SH NAME
viewnior \- simple, fast and elegant image viewer
.SH SYNOPSIS
.B viewnior
[\fIOPTIONS\fR]
[\fIFILES\fR|\fIFOLDERS\fR]...
.SH DESCRIPTION
Viewnior is an image viewer program. Created to be simple, 
fast and elegant. It's minimalistic interface provides more 
screenspace for your images.
.SH OPTIONS
.TP
\fB\-\-slideshow\fR
Start in slideshow
.TP
\fB\-\-fullscreen\fR
Start in full screen mode
.TP
\fB\-?\fR, \fB\-\-help\fR
Show this help and exit
.TP
\fB\-\-version\fR
Show version information and exit
.SH KEYBOARD SHORTCUT
.IP "Ctrl-o"
Open an image
.IP "Ctrl-f"
Open a folder
.IP "Ctrl-w, q"
Close Viewnior
.IP "Ctrl-s"
Save changes
.IP "Ctrl-r"
Rotate image clockwise
.IP "Ctrl-R"
Rotate image anti clockwise
.IP "Ctrl-F8"
Set the selected image as the desktop background
.IP "F5"
Toggle slideshow
.IP "F11"
Toggle fullscreen
.IP "Del"
Delete the current file
.IP "+, ="
Zoom in
.IP "-"
Zoom out
.IP "c"
Crop image
.IP "h"
Flip horizontally
.IP "v"
Flip vertically
.IP "Space, Right"
Go to next image
.IP "Backspace, Left"
Go to previous image
.IP "Alt-Home"
Go to first image
.IP "Alt-End"
Go to last image
.IP "Ctrl-0"
Set image size to 100%
.IP "0"
Fit the image
.IP "Alt-Return"
Show info about the current file
.SH "SEE ALSO"
.PP
Website: http://siyanpanayotov.com/project/viewnior/
.SH AUTHOR
Viewnior was written by Siyan Panayotov <contact@siyanpanayotov.com>.

.PP
This manual page was written by Siyan Panayotov <contact@siyanpanayotov.com>.
